export const sample_foods = [
  {
    id: 1,
    name: "Margherita Pizza",
    cookTime: 20,
    price: 12.99,
    favorite: true,
    origins: ["Italy"],
    stars: 4.5,
    imageUrl: "food-1.jpg",
    tags: ["Pizza", "Italian", "Dinner"],
    desc: "Indulge in the classic flavors of Italy with our Margherita Pizza. This delightful dish features a thin crust topped with fresh tomatoes, mozzarella, and fragrant basil leaves. Each bite is a burst of authentic Italian taste, making it a perfect choice for a satisfying dinner experience.",
  },
  {
    id: 2,
    name: "Chicken Alfredo Pasta",
    cookTime: 30,
    price: 15.99,
    favorite: false,
    origins: ["Italy"],
    stars: 4.2,
    imageUrl: "food-2.jpg",
    tags: ["Pasta", "Italian", "Dinner"],
    desc: "Savor the rich and creamy goodness of our Chicken Alfredo Pasta. Cooked to perfection, this Italian-inspired dish features al dente pasta coated in a velvety Alfredo sauce. Tender pieces of chicken add a savory touch, creating a comforting and flavorful dining experience for pasta enthusiasts.",
  },
  {
    id: 3,
    name: "Vegetarian Stir-Fry",
    cookTime: 25,
    price: 10.99,
    favorite: true,
    origins: ["Asia"],
    stars: 4.8,
    imageUrl: "food-3.jpg",
    tags: ["Vegetarian", "Asian", "Lunch"],
    desc: "Embark on a culinary journey with our Vegetarian Stir-Fry, a delightful Asian-inspired dish. Fresh vegetables are wok-tossed to perfection, creating a colorful and nutritious medley. The combination of vibrant flavors and textures makes it an ideal choice for a satisfying and healthy lunch.",
  },
  {
    id: 4,
    name: "Classic Hamburger",
    cookTime: 15,
    price: 8.99,
    favorite: false,
    origins: ["USA"],
    stars: 4.0,
    imageUrl: "food-4.jpg",
    tags: ["Fast Food", "Lunch", "Hamburger"],
    desc: "Satisfy your cravings with our Classic Hamburger, an iconic American favorite. This mouthwatering creation features a juicy beef patty, fresh lettuce, ripe tomatoes, and a special sauce, all sandwiched between soft burger buns. It's a timeless choice for a quick and delicious lunch.",
  },
  {
    id: 5,
    name: "Sushi Platter",
    cookTime: 40,
    price: 24.99,
    favorite: true,
    origins: ["Japan"],
    stars: 4.7,
    imageUrl: "food-5.jpg",
    tags: ["Sushi", "Japanese", "Dinner"],
    desc: "Elevate your dining experience with our Sushi Platter, a stunning showcase of Japanese culinary artistry. Immerse yourself in the delicate flavors of fresh fish, perfectly seasoned rice, and seaweed. Each piece is a masterpiece, offering a symphony of tastes for a delightful dinner.",
  },
  {
    id: 6,
    name: "Mango Sticky Rice",
    cookTime: 15,
    price: 7.99,
    favorite: false,
    origins: ["Thailand"],
    stars: 4.3,
    imageUrl: "food-6.jpg",
    tags: ["Dessert", "Thai", "Snack"],
    desc: "Treat your taste buds to the exotic sweetness of our Mango Sticky Rice, a beloved Thai dessert. Fragrant sticky rice is paired with ripe mango slices, creating a harmonious blend of textures and flavors. It's a delightful way to conclude your meal or enjoy as a satisfying snack.",
  },
  {
    id: 7,
    name: "Caesar Salad",
    cookTime: 15,
    price: 9.99,
    favorite: false,
    origins: ["USA"],
    stars: 4.2,
    imageUrl: "food-7.jpg",
    tags: ["Salad", "Lunch", "Healthy"],
    desc: "Indulge in a crisp and refreshing experience with our Caesar Salad, a timeless classic from the USA. Crisp romaine lettuce is tossed with savory Caesar dressing, Parmesan cheese, and croutons. This light and healthy salad make for a perfect lunch option, combining simplicity and deliciousness.",
  },
  {
    id: 8,
    name: "Beef Biryani",
    cookTime: 35,
    price: 16.99,
    favorite: true,
    origins: ["India"],
    stars: 4.6,
    imageUrl: "food-8.jpg",
    tags: ["Rice", "Indian", "Dinner"],
    desc: "Delight your senses with the aromatic flavors of our Beef Biryani, a traditional Indian dish that is a feast for the palate. Fragrant basmati rice is layered with succulent beef, aromatic spices, and caramelized onions. It's a hearty and satisfying dinner choice, offering a taste of authentic Indian cuisine.",
  },
  {
    id: 9,
    name: "Caprese Salad",
    cookTime: 10,
    price: 11.99,
    favorite: false,
    origins: ["Italy"],
    stars: 4.4,
    imageUrl: "food-9.jpg",
    tags: ["Salad", "Italian", "Appetizer"],
    desc: "Transport yourself to the heart of Italy with our Caprese Salad, a quintessential Italian appetizer. This vibrant salad showcases the simplicity of fresh ingredients—ripe tomatoes, creamy mozzarella, and fragrant basil. Drizzled with extra-virgin olive oil and balsamic glaze, every bite is a burst of Mediterranean flavors, making it an ideal choice for a light and refreshing start to your meal.",
  },
  {
    id: 10,
    name: "Chicken Teriyaki Bowl",
    cookTime: 25,
    price: 13.99,
    favorite: true,
    origins: ["Japan"],
    stars: 4.7,
    imageUrl: "food-10.jpg",
    tags: ["Chicken", "Japanese", "Lunch"],
    desc: "Experience the savory delight of our Chicken Teriyaki Bowl, inspired by the flavors of Japan. Succulent pieces of grilled chicken are glazed in a rich and sweet teriyaki sauce, served atop a bed of steamed rice. This hearty dish is a perfect choice for a satisfying and flavorful lunch, combining the best of Japanese culinary traditions.",
  },
  {
    id: 11,
    name: "Spinach and Feta Stuffed Chicken",
    cookTime: 40,
    price: 18.99,
    favorite: false,
    origins: ["Mediterranean"],
    stars: 4.5,
    imageUrl: "food-11.jpg",
    tags: ["Chicken", "Mediterranean", "Dinner"],
    desc: "Indulge in the culinary richness of our Spinach and Feta Stuffed Chicken, a Mediterranean-inspired delicacy. Tender chicken breasts are carefully stuffed with a flavorful combination of spinach and feta cheese, then baked to perfection. This delightful dish is a symphony of textures and tastes, making it a standout choice for a satisfying dinner.",
  },
  {
    id: 12,
    name: "Chocolate Fondue",
    cookTime: 20,
    price: 14.99,
    favorite: true,
    origins: ["Switzerland"],
    stars: 4.8,
    imageUrl: "food-12.jpg",
    tags: ["Dessert", "Swiss", "Chocolate"],
    desc: "Conclude your meal on a sweet note with our Chocolate Fondue, a decadent Swiss dessert experience. Indulge in the velvety richness of melted chocolate served alongside an array of delightful dippables. Whether it's fruits, marshmallows, or cake, each dip is a heavenly blend of sweetness and satisfaction, making it a delightful treat for chocolate lovers.",
  },
];

export const sample_tags = [
  { name: "All", count: 6 },
  { name: "Fast Food", count: 4 },
  { name: "Pizza", count: 2 },
  { name: "Lunch", count: 3 },
  { name: "Hamburger", count: 1 },
  { name: "Dessert", count: 1 },
  { name: "Dinner", count: 3 },
  { name: "Pasta", count: 1 },
];

export const sample_users = [
  {
    id: 1,
    name: "John Doe",
    email: "john@gmail.com",
    password: "12345",
    address: "Toronto On",
    isAdmin: false,
  },
  {
    id: 2,
    name: "Jane Doe",
    email: "jane@gmail.com",
    password: "12345",
    address: "Shanghai",
    isAdmin: true,
  },
];
